kafka:
  topic:
    master: master-topic
    replica: replica-topic
  group-id: group-consumer

spring:
  application:
    name: consumer
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "com.pg.replication-assignor.common.event"

management:
  endpoints:
    enabled-by-default: true

application:
  instance:
    max_assignments: 10