spring:
  kafka:
    bootstrap-servers: localhost:19092

application:
  instance:
    id: "local-consumer-${server.port}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true