apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: replica-topic
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
  config:
    min.cleanable.dirty.ratio: 0.001
    cleanup.policy: compact
    segment.ms: 1000
    retention.ms: 1000
    delete.retention.ms: 1000

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: master-topic
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
